//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDMakerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TDMakerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_cloud {
            get {
                object obj = ResourceManager.GetObject("application-cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_monitor {
            get {
                object obj = ResourceManager.GetObject("application-monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_task {
            get {
                object obj = ResourceManager.GetObject("application-task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrent Description Maker.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crown {
            get {
                object obj = ResourceManager.GetObject("crown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk__pencil {
            get {
                object obj = ResourceManager.GetObject("disk--pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk_return {
            get {
                object obj = ResourceManager.GetObject("disk-return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_copy {
            get {
                object obj = ResourceManager.GetObject("document-copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder-open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_document_text {
            get {
                object obj = ResourceManager.GetObject("folder-open-document-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_film {
            get {
                object obj = ResourceManager.GetObject("folder-open-film", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GenuineAdvIcon {
            get {
                object obj = ResourceManager.GetObject("GenuineAdvIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenuineAdvLogo {
            get {
                object obj = ResourceManager.GetObject("GenuineAdvLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_16_xp {
            get {
                object obj = ResourceManager.GetObject("info_16_xp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap layout_design {
            get {
                object obj = ResourceManager.GetObject("layout-design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will rewrite old copies of TDMaker created Templates. Your own templates will not be affected. 
        ///
        ///Are you sure?.
        /// </summary>
        internal static string MainWindow_btnTemplatesRewrite_Click_ {
            get {
                return ResourceManager.GetString("MainWindow_btnTemplatesRewrite_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string MainWindow_bwApp_RunWorkerCompleted_Ready_ {
            get {
                return ResourceManager.GetString("MainWindow_bwApp_RunWorkerCompleted_Ready_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready. One or more tasks failed..
        /// </summary>
        internal static string MainWindow_bwApp_RunWorkerCompleted_Ready__One_or_more_tasks_failed_ {
            get {
                return ResourceManager.GetString("MainWindow_bwApp_RunWorkerCompleted_Ready__One_or_more_tasks_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of TDMaker is available. 
        ///Would you like to download and install it?.
        /// </summary>
        internal static string MainWindow_CheckUpdate_ {
            get {
                return ResourceManager.GetString("MainWindow_CheckUpdate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download FFmpeg..
        /// </summary>
        internal static string MainWindow_DownloaderForm_InstallRequested_Failed_to_download_FFmpeg_ {
            get {
                return ResourceManager.GetString("MainWindow_DownloaderForm_InstallRequested_Failed_to_download_FFmpeg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully downloaded FFmpeg..
        /// </summary>
        internal static string MainWindow_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_ {
            get {
                return ResourceManager.GetString("MainWindow_DownloaderForm_InstallRequested_Successfully_downloaded_FFmpeg_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing Publish info to File is recommended when analysing multiple files or folders. 
        ///
        ///Would you like to turn this feature on?.
        /// </summary>
        internal static string MainWindow_LoadMedia_ {
            get {
                return ResourceManager.GetString("MainWindow_LoadMedia_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg is not configured. 
        ///
        ///Would you like to download the latest FFmpeg?.
        /// </summary>
        internal static string MainWindow_MainWindow_Shown_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Shown_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications (ffmpeg.exe)|ffmpeg.exe.
        /// </summary>
        internal static string MainWindow_MainWindow_Shown_Applications__ffmpeg_exe__ffmpeg_exe {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Shown_Applications__ffmpeg_exe__ffmpeg_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications (mplayer.exe)|mplayer.exe.
        /// </summary>
        internal static string MainWindow_MainWindow_Shown_Applications__mplayer_exe__mplayer_exe {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Shown_Applications__mplayer_exe__mplayer_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for ffmpeg.exe.
        /// </summary>
        internal static string MainWindow_MainWindow_Shown_Browse_for_ffmpeg_exe {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Shown_Browse_for_ffmpeg_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for mplayer.exe or download from .
        /// </summary>
        internal static string MainWindow_MainWindow_Shown_Browse_for_mplayer_exe_or_download_from_ {
            get {
                return ResourceManager.GetString("MainWindow_MainWindow_Shown_Browse_for_mplayer_exe_or_download_from_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Media file....
        /// </summary>
        internal static string MainWindow_OpenFile_Browse_for_Media_file___ {
            get {
                return ResourceManager.GetString("MainWindow_OpenFile_Browse_for_Media_file___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for media disc folder....
        /// </summary>
        internal static string MainWindow_OpenFolder_Browse_for_media_disc_folder___ {
            get {
                return ResourceManager.GetString("MainWindow_OpenFolder_Browse_for_media_disc_folder___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Media Info As....
        /// </summary>
        internal static string MainWindow_tcMain_SelectedIndexChanged__Save_Media_Info_As___ {
            get {
                return ResourceManager.GetString("MainWindow_tcMain_SelectedIndexChanged__Save_Media_Info_As___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save Publish Info As....
        /// </summary>
        internal static string MainWindow_tcMain_SelectedIndexChanged__Save_Publish_Info_As___ {
            get {
                return ResourceManager.GetString("MainWindow_tcMain_SelectedIndexChanged__Save_Publish_Info_As___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;description.
        /// </summary>
        internal static string MainWindow_tmrStatus_Tick_Create__description {
            get {
                return ResourceManager.GetString("MainWindow_tmrStatus_Tick_Create__description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp;torrent.
        /// </summary>
        internal static string MainWindow_tmrStatus_Tick_Create__torrent {
            get {
                return ResourceManager.GetString("MainWindow_tmrStatus_Tick_Create__torrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors were found:
        ///
        ///.
        /// </summary>
        internal static string MainWindow_ValidateInput_ {
            get {
                return ResourceManager.GetString("MainWindow_ValidateInput_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.txt)|*.txt.
        /// </summary>
        internal static string MainWindow_WriteMediaInfo_Text_Files____txt____txt {
            get {
                return ResourceManager.GetString("MainWindow_WriteMediaInfo_Text_Files____txt____txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrench_screwdriver {
            get {
                object obj = ResourceManager.GetObject("wrench-screwdriver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
